
// enter your API Gateway URL
@URL=https://api.tranvandat-deploy.click

POST {{URL}} HTTP/1.1
Content-Type: application/json
Accept: "application/json"

{
  "sourceLang": "en",
  "targetLang": "ja",
  "sourceText": "Fuck You, Just Joke, I Test Transaltion Service."
}

###

GET {{URL}} HTTP/1.1
Content-Type: application/json
Accept: "application/json"